services:
  # A Docker web service
  - type: web
    name: langflow
    plan: pro
    runtime: docker
    dockerfilePath: ./docker/render.Dockerfile
    repo: https://github.com/headlinevc/langflow
    branch: main
    healthCheckPath: /health
    numInstances: 3
    autoDeploy: false
    envVars:
      - key: LANGFLOW_DATABASE_URL
        fromDatabase:
          name: langflow-db
          property: connectionString
      - key: LANGFLOW_HOST
        value: 0.0.0.0
      - key: LANGFLOW_PORT
        # default render port https://docs.render.com/web-services#port-binding
        value: 10000
      - key: LANGFLOW_LOG_LEVEL
        value: INFO

databases:
  - name: langflow-db
    plan: basic-1gb
    previewPlan: basic-256mb
    databaseName: langflow_db_production
    user: langflow
    diskSizeGB: 10
